# Generated by Django 4.2.7 on 2023-12-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
