# Generated by Django 4.2.7 on 2024-01-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='facebook',
            field=models.CharField(blank=True, help_text='Enter Facebook link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='instagram',
            field=models.CharField(blank=True, help_text='Enter Instagram link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='qr',
            field=models.ImageField(blank=True, help_text='Upload QR code image', null=True, upload_to='item_images'),
        ),
    ]
